[0m22:04:09.234851 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DA2467F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DA2451790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DA2451510>]}


============================== 22:04:09.242424 | ce2c1d0f-ec03-4885-8b55-1279ffe5c131 ==============================
[0m22:04:09.242424 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:04:09.243432 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/USER/Alta/belajar-bc/dbt/dbt-new/dbt-profiles', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt clean', 'send_anonymous_usage_stats': 'True'}
[0m22:04:09.244436 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\USER\Alta\belajar-bc\dbt\dbt-new\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:04:09.245870 [debug] [MainThread]: Command `dbt clean` failed at 22:04:09.245870 after 0.08 seconds
[0m22:04:09.245870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D9D89DA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DA2466F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D9D213890>]}
[0m22:04:09.246880 [debug] [MainThread]: Flushing usage events
[0m12:55:06.257537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D2C71F4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D2C751510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D2C76E150>]}


============================== 12:55:06.260985 | afafbb8a-ee83-414d-bb24-db5507b7d693 ==============================
[0m12:55:06.260985 [info ] [MainThread]: Running with dbt=1.8.4
[0m12:55:06.262003 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/USER/Alta/belajar-bc/dbt/dbt-new/dbt-profiles', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt clean', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:55:06.263007 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\USER\Alta\belajar-bc\dbt\dbt-new\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:55:06.264527 [debug] [MainThread]: Command `dbt clean` failed at 12:55:06.264527 after 0.06 seconds
[0m12:55:06.264527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D2C4F64D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D273139D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D27312D10>]}
[0m12:55:06.265531 [debug] [MainThread]: Flushing usage events
